+ AsyncDNS

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1240,6 +1240,7 @@ Optional Packages:
   --with-cyrus-sasl=PREFIX
                           Cyrus SASL library
   --with-mysql=PREFIX     MySQL client library
+  --with-udns=PREFIX      UDNS (DNS Resolver Library)
 
 Some influential environment variables:
   CC          C compiler command
@@ -4497,7 +4498,6 @@ fi
 
 
 
-echo SASL: $SASL
 
 
 # Check whether --with-gsasl was given.
@@ -4758,9 +4758,84 @@ fi
 
 
 
-# Checks for header files.
 
-# Checks for typedefs, structures, and compiler characteristics.
+# Check whether --with-udns was given.
+if test "${with_udns+set}" = set; then
+  withval=$with_udns;
+		CPPFLAGS="$CPPFLAGS  -I$withval/include"
+		LDFLAGS="$LDFLAGS -L$withval/lib -Wl,-rpath=$withval/lib"
+
+fi
+
+
+{ echo "$as_me:$LINENO: checking for main in -ludns" >&5
+echo $ECHO_N "checking for main in -ludns... $ECHO_C" >&6; }
+if test "${ac_cv_lib_udns_main+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-ludns  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+
+int
+main ()
+{
+return main ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_udns_main=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_udns_main=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_udns_main" >&5
+echo "${ECHO_T}$ac_cv_lib_udns_main" >&6; }
+if test $ac_cv_lib_udns_main = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBUDNS 1
+_ACEOF
+
+  LIBS="-ludns $LIBS"
+
+else
+  { { echo "$as_me:$LINENO: error: UDNS (DNS Resolver Library) required" >&5
+echo "$as_me: error: UDNS (DNS Resolver Library) required" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
 
 ac_config_files="$ac_config_files Makefile"
 
