nanosoft via svn:externals

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -640,6 +640,10 @@ INSTALL_DATA
 AR
 RANLIB
 MKDIR
+SASL
+SASL_LIBS
+WITH_MYSQL
+MYSQL_LIBS
 LIBOBJS
 LTLIBOBJS'
 ac_subst_files=''
@@ -1231,7 +1235,10 @@ Optional Packages:
   --with-expat=PREFIX     expat XML parser
   --with-pthread=PREFIX   pthread
   --with-nanosoft=PREFIX  prefix to nanosoft libraries
+  --with-sasl=TYPE        switch SASL library (cyrus, gnu)
   --with-gsasl=PREFIX     GNU SASL library
+  --with-cyrus-sasl=PREFIX
+                          Cyrus SASL library
   --with-mysql=PREFIX     MySQL client library
 
 Some influential environment variables:
@@ -1709,6 +1716,8 @@ ac_configure="$SHELL $ac_aux_dir/configure"  # Please don't use this var.
 
 
 ac_config_headers="$ac_config_headers src/include/config.h"
+
+ac_config_headers="$ac_config_headers nanosoft/src/include/nanosoft/config.h"
 
 
 # Make sure we can run config.sub.
@@ -4448,144 +4457,47 @@ if test "${with_nanosoft+set}" = set; then
 
 fi
 
+#AC_CHECK_LIB(nanosoft, main, [], [AC_ERROR(nanosoft library is required)])
+#AC_CHECK_LIB(netd, main, [], [AC_ERROR(nanosoft netd library is required)])
 
-{ echo "$as_me:$LINENO: checking for main in -lnanosoft" >&5
-echo $ECHO_N "checking for main in -lnanosoft... $ECHO_C" >&6; }
-if test "${ac_cv_lib_nanosoft_main+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-lnanosoft  $LIBS"
-cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
+SASL=none
+SASL_LIBS=""
 
-
-int
-main ()
-{
-return main ();
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (ac_try="$ac_link"
-case "(($ac_try" in
-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-  *) ac_try_echo=$ac_try;;
-esac
-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
-  (eval "$ac_link") 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } && {
-	 test -z "$ac_cxx_werror_flag" ||
-	 test ! -s conftest.err
-       } && test -s conftest$ac_exeext &&
-       $as_test_x conftest$ac_exeext; then
-  ac_cv_lib_nanosoft_main=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-	ac_cv_lib_nanosoft_main=no
-fi
-
-rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
-      conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-{ echo "$as_me:$LINENO: result: $ac_cv_lib_nanosoft_main" >&5
-echo "${ECHO_T}$ac_cv_lib_nanosoft_main" >&6; }
-if test $ac_cv_lib_nanosoft_main = yes; then
-  cat >>confdefs.h <<_ACEOF
-#define HAVE_LIBNANOSOFT 1
+# Check whether --with-sasl was given.
+if test "${with_sasl+set}" = set; then
+  withval=$with_sasl;
+		SASL=$withval
+		case "$SASL" in
+		gnu)
+			cat >>confdefs.h <<\_ACEOF
+#define WITH_GNU_SASL 1
 _ACEOF
 
-  LIBS="-lnanosoft $LIBS"
+			SASL_LIBS="-lgsasl"
+			;;
+		cyrus)
+			cat >>confdefs.h <<\_ACEOF
+#define WITH_CYRUS_SASL 1
+_ACEOF
 
-else
-  { { echo "$as_me:$LINENO: error: nanosoft library is required" >&5
-echo "$as_me: error: nanosoft library is required" >&2;}
+			SASL_LIBS="-lsasl2"
+			;;
+		*)
+			{ { echo "$as_me:$LINENO: error: switch SASL library (cyrus, gnu, none)" >&5
+echo "$as_me: error: switch SASL library (cyrus, gnu, none)" >&2;}
    { (exit 1); exit 1; }; }
-fi
-
-
-{ echo "$as_me:$LINENO: checking for main in -lnetd" >&5
-echo $ECHO_N "checking for main in -lnetd... $ECHO_C" >&6; }
-if test "${ac_cv_lib_netd_main+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-lnetd  $LIBS"
-cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-
-
-int
-main ()
-{
-return main ();
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (ac_try="$ac_link"
-case "(($ac_try" in
-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-  *) ac_try_echo=$ac_try;;
-esac
-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
-  (eval "$ac_link") 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } && {
-	 test -z "$ac_cxx_werror_flag" ||
-	 test ! -s conftest.err
-       } && test -s conftest$ac_exeext &&
-       $as_test_x conftest$ac_exeext; then
-  ac_cv_lib_netd_main=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-	ac_cv_lib_netd_main=no
-fi
-
-rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
-      conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-{ echo "$as_me:$LINENO: result: $ac_cv_lib_netd_main" >&5
-echo "${ECHO_T}$ac_cv_lib_netd_main" >&6; }
-if test $ac_cv_lib_netd_main = yes; then
-  cat >>confdefs.h <<_ACEOF
-#define HAVE_LIBNETD 1
-_ACEOF
-
-  LIBS="-lnetd $LIBS"
+			;;
+		esac
 
 else
-  { { echo "$as_me:$LINENO: error: nanosoft netd library is required" >&5
-echo "$as_me: error: nanosoft netd library is required" >&2;}
-   { (exit 1); exit 1; }; }
+
+		SASL=gnu
+
 fi
 
+
+
+echo SASL: $SASL
 
 
 # Check whether --with-gsasl was given.
@@ -4596,7 +4508,6 @@ if test "${with_gsasl+set}" = set; then
 
 fi
 
-# TODO AC_CHECK_HEADER(gsasl.h, [], [AC_ERROR(GNU SASL library required)])
 
 { echo "$as_me:$LINENO: checking for main in -lgsasl" >&5
 echo $ECHO_N "checking for main in -lgsasl... $ECHO_C" >&6; }
@@ -4661,30 +4572,120 @@ _ACEOF
   LIBS="-lgsasl $LIBS"
 
 else
-  { { echo "$as_me:$LINENO: error: GNU SASL library required" >&5
+
+		if test "$SASL" = "gnu"; then
+			{ { echo "$as_me:$LINENO: error: GNU SASL library required" >&5
 echo "$as_me: error: GNU SASL library required" >&2;}
    { (exit 1); exit 1; }; }
+		fi
+
 fi
 
 
 
-# Check whether --with-mysql was given.
-if test "${with_mysql+set}" = set; then
-  withval=$with_mysql;
+# Check whether --with-cyrus-sasl was given.
+if test "${with_cyrus_sasl+set}" = set; then
+  withval=$with_cyrus_sasl;
 		CPPFLAGS="$CPPFLAGS  -I$withval/include"
 		LDFLAGS="$LDFLAGS -L$withval/lib -Wl,-rpath=$withval/lib"
 
 fi
 
-# TODO AC_CHECK_HEADER(mysql.h, [], [AC_ERROR(MySQL client library required)])
 
-{ echo "$as_me:$LINENO: checking for mysql_real_connect in -lmysqlclient" >&5
-echo $ECHO_N "checking for mysql_real_connect in -lmysqlclient... $ECHO_C" >&6; }
-if test "${ac_cv_lib_mysqlclient_mysql_real_connect+set}" = set; then
+{ echo "$as_me:$LINENO: checking for main in -lsasl2" >&5
+echo $ECHO_N "checking for main in -lsasl2... $ECHO_C" >&6; }
+if test "${ac_cv_lib_sasl2_main+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   ac_check_lib_save_LIBS=$LIBS
-LIBS="-lmysqlclient  $LIBS"
+LIBS="-lsasl2  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+
+int
+main ()
+{
+return main ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_sasl2_main=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_sasl2_main=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_sasl2_main" >&5
+echo "${ECHO_T}$ac_cv_lib_sasl2_main" >&6; }
+if test $ac_cv_lib_sasl2_main = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBSASL2 1
+_ACEOF
+
+  LIBS="-lsasl2 $LIBS"
+
+else
+
+		if test "$SASL" = "cyrus"; then
+			{ { echo "$as_me:$LINENO: error: Cyrus SASL library required" >&5
+echo "$as_me: error: Cyrus SASL library required" >&2;}
+   { (exit 1); exit 1; }; }
+		fi
+
+fi
+
+
+WITH_MYSQL=yes
+MYSQL_LIBS=""
+
+# Check whether --with-mysql was given.
+if test "${with_mysql+set}" = set; then
+  withval=$with_mysql;
+		if test "$withval" != "yes"; then
+			CPPFLAGS="$CPPFLAGS  -I$withval/include"
+			LDFLAGS="$LDFLAGS -L$withval/lib -Wl,-rpath=$withval/lib"
+		fi
+		WITH_MYSQL=yes
+
+fi
+
+{ echo "$as_me:$LINENO: checking for mysql_real_connect in -lmysqlclient_r" >&5
+echo $ECHO_N "checking for mysql_real_connect in -lmysqlclient_r... $ECHO_C" >&6; }
+if test "${ac_cv_lib_mysqlclient_r_mysql_real_connect+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lmysqlclient_r  $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -4725,107 +4726,36 @@ eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
 	 test ! -s conftest.err
        } && test -s conftest$ac_exeext &&
        $as_test_x conftest$ac_exeext; then
-  ac_cv_lib_mysqlclient_mysql_real_connect=yes
+  ac_cv_lib_mysqlclient_r_mysql_real_connect=yes
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-	ac_cv_lib_mysqlclient_mysql_real_connect=no
+	ac_cv_lib_mysqlclient_r_mysql_real_connect=no
 fi
 
 rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
       conftest$ac_exeext conftest.$ac_ext
 LIBS=$ac_check_lib_save_LIBS
 fi
-{ echo "$as_me:$LINENO: result: $ac_cv_lib_mysqlclient_mysql_real_connect" >&5
-echo "${ECHO_T}$ac_cv_lib_mysqlclient_mysql_real_connect" >&6; }
-if test $ac_cv_lib_mysqlclient_mysql_real_connect = yes; then
-  cat >>confdefs.h <<_ACEOF
-#define HAVE_LIBMYSQLCLIENT 1
-_ACEOF
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_mysqlclient_r_mysql_real_connect" >&5
+echo "${ECHO_T}$ac_cv_lib_mysqlclient_r_mysql_real_connect" >&6; }
+if test $ac_cv_lib_mysqlclient_r_mysql_real_connect = yes; then
 
-  LIBS="-lmysqlclient $LIBS"
+		MYSQL_LIBS="-lmysqlclient_r"
+		WITH_MYSQL="yes"
 
 else
-  { { echo "$as_me:$LINENO: error: MySQL client library required" >&5
-echo "$as_me: error: MySQL client library required" >&2;}
+
+		if test "$WITH_MYSQL" = "yes"; then
+			{ { echo "$as_me:$LINENO: error: MySQL client library not found" >&5
+echo "$as_me: error: MySQL client library not found" >&2;}
    { (exit 1); exit 1; }; }
+		fi
+
 fi
 
 
-{ echo "$as_me:$LINENO: checking for mysql_real_query in -lmysqlclient" >&5
-echo $ECHO_N "checking for mysql_real_query in -lmysqlclient... $ECHO_C" >&6; }
-if test "${ac_cv_lib_mysqlclient_mysql_real_query+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-lmysqlclient  $LIBS"
-cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-
-/* Override any GCC internal prototype to avoid an error.
-   Use char because int might match the return type of a GCC
-   builtin and then its argument prototype would still apply.  */
-#ifdef __cplusplus
-extern "C"
-#endif
-char mysql_real_query ();
-int
-main ()
-{
-return mysql_real_query ();
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (ac_try="$ac_link"
-case "(($ac_try" in
-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-  *) ac_try_echo=$ac_try;;
-esac
-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
-  (eval "$ac_link") 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } && {
-	 test -z "$ac_cxx_werror_flag" ||
-	 test ! -s conftest.err
-       } && test -s conftest$ac_exeext &&
-       $as_test_x conftest$ac_exeext; then
-  ac_cv_lib_mysqlclient_mysql_real_query=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-	ac_cv_lib_mysqlclient_mysql_real_query=no
-fi
-
-rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
-      conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-{ echo "$as_me:$LINENO: result: $ac_cv_lib_mysqlclient_mysql_real_query" >&5
-echo "${ECHO_T}$ac_cv_lib_mysqlclient_mysql_real_query" >&6; }
-if test $ac_cv_lib_mysqlclient_mysql_real_query = yes; then
-  cat >>confdefs.h <<_ACEOF
-#define HAVE_LIBMYSQLCLIENT 1
-_ACEOF
-
-  LIBS="-lmysqlclient $LIBS"
-
-else
-  { { echo "$as_me:$LINENO: error: MySQL client library required" >&5
-echo "$as_me: error: MySQL client library required" >&2;}
-   { (exit 1); exit 1; }; }
-fi
 
 
 # Checks for header files.
@@ -5388,6 +5318,7 @@ for ac_config_target in $ac_config_targets
 do
   case $ac_config_target in
     "src/include/config.h") CONFIG_HEADERS="$CONFIG_HEADERS src/include/config.h" ;;
+    "nanosoft/src/include/nanosoft/config.h") CONFIG_HEADERS="$CONFIG_HEADERS nanosoft/src/include/nanosoft/config.h" ;;
     "Makefile") CONFIG_FILES="$CONFIG_FILES Makefile" ;;
 
   *) { { echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
@@ -5512,11 +5443,15 @@ INSTALL_DATA!$INSTALL_DATA$ac_delim
 AR!$AR$ac_delim
 RANLIB!$RANLIB$ac_delim
 MKDIR!$MKDIR$ac_delim
+SASL!$SASL$ac_delim
+SASL_LIBS!$SASL_LIBS$ac_delim
+WITH_MYSQL!$WITH_MYSQL$ac_delim
+MYSQL_LIBS!$MYSQL_LIBS$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 64; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 68; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
