+ configure.mysql

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1232,6 +1232,7 @@ Optional Packages:
   --with-pthread=PREFIX   pthread
   --with-nanosoft=PREFIX  prefix to nanosoft libraries
   --with-gsasl=PREFIX     GNU SASL library
+  --with-mysql=PREFIX     MySQL client library
 
 Some influential environment variables:
   CC          C compiler command
@@ -4285,7 +4286,7 @@ fi
 if test "${with_expat+set}" = set; then
   withval=$with_expat;
 		CXXFLAGS="$CXXFLAGS -I$withval/include"
-		LDFLAGS="$LDFLAGS -L$withval/lib"
+		LDFLAGS="$LDFLAGS -L$withval/lib -Wl,-rpath=$withval/lib"
 
 fi
 
@@ -4364,7 +4365,7 @@ fi
 if test "${with_pthread+set}" = set; then
   withval=$with_pthread;
 		CXXFLAGS="$CXXFLAGS -I$withval/include"
-		LDFLAGS="$LDFLAGS -L$withval/lib"
+		LDFLAGS="$LDFLAGS -L$withval/lib -Wl,-rpath=$withval/lib"
 
 fi
 
@@ -4443,7 +4444,7 @@ fi
 if test "${with_nanosoft+set}" = set; then
   withval=$with_nanosoft;
 		CXXFLAGS="$CXXFLAGS -I$withval/include"
-		LDFLAGS="$LDFLAGS -L$withval/lib"
+		LDFLAGS="$LDFLAGS -L$withval/lib -Wl,-rpath=$withval/lib"
 
 fi
 
@@ -4662,6 +4663,167 @@ _ACEOF
 else
   { { echo "$as_me:$LINENO: error: GNU SASL library required" >&5
 echo "$as_me: error: GNU SASL library required" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+
+
+# Check whether --with-mysql was given.
+if test "${with_mysql+set}" = set; then
+  withval=$with_mysql;
+		CPPFLAGS="$CPPFLAGS  -I$withval/include"
+		LDFLAGS="$LDFLAGS -L$withval/lib -Wl,-rpath=$withval/lib"
+
+fi
+
+# TODO AC_CHECK_HEADER(mysql.h, [], [AC_ERROR(MySQL client library required)])
+
+{ echo "$as_me:$LINENO: checking for mysql_real_connect in -lmysqlclient_r" >&5
+echo $ECHO_N "checking for mysql_real_connect in -lmysqlclient_r... $ECHO_C" >&6; }
+if test "${ac_cv_lib_mysqlclient_r_mysql_real_connect+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lmysqlclient_r  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char mysql_real_connect ();
+int
+main ()
+{
+return mysql_real_connect ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_mysqlclient_r_mysql_real_connect=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_mysqlclient_r_mysql_real_connect=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_mysqlclient_r_mysql_real_connect" >&5
+echo "${ECHO_T}$ac_cv_lib_mysqlclient_r_mysql_real_connect" >&6; }
+if test $ac_cv_lib_mysqlclient_r_mysql_real_connect = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBMYSQLCLIENT_R 1
+_ACEOF
+
+  LIBS="-lmysqlclient_r $LIBS"
+
+else
+  { { echo "$as_me:$LINENO: error: MySQL client library required" >&5
+echo "$as_me: error: MySQL client library required" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+
+{ echo "$as_me:$LINENO: checking for mysql_real_query in -lmysqlclient_r" >&5
+echo $ECHO_N "checking for mysql_real_query in -lmysqlclient_r... $ECHO_C" >&6; }
+if test "${ac_cv_lib_mysqlclient_r_mysql_real_query+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lmysqlclient_r  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char mysql_real_query ();
+int
+main ()
+{
+return mysql_real_query ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_mysqlclient_r_mysql_real_query=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_mysqlclient_r_mysql_real_query=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_mysqlclient_r_mysql_real_query" >&5
+echo "${ECHO_T}$ac_cv_lib_mysqlclient_r_mysql_real_query" >&6; }
+if test $ac_cv_lib_mysqlclient_r_mysql_real_query = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBMYSQLCLIENT_R 1
+_ACEOF
+
+  LIBS="-lmysqlclient_r $LIBS"
+
+else
+  { { echo "$as_me:$LINENO: error: MySQL client library required" >&5
+echo "$as_me: error: MySQL client library required" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
